---
driver:
  name: qemu


platforms:
- name: jessie
  driver:
    image: /home/simon/qemu_images/jessie.qcow2

suites:
- name: default
  run_list:
    - recipe[xil-virtualmachines::default]
  attributes:
    xil:
      virtualmachines:
        testmachine:
          ensure: "running"
          template: "archtemplate"
          temporary: true
          ip : "192.168.1.3"
          gateway : "192.168.1.1"
