---
driver:
  name: qemu


platforms:
- name: arch
  driver:
    image: arch.qcow2
    display: gtk
    bios: /usr/share/ovmf/ovmf_x64.bin    

provisioner:
    name: chef_zero

    
suites:
- name: default
  run_list:
    - recipe[xil-init::default]
  attributes:
