---
driver:
  name: qemu


platforms:
- name: arch
  driver:
    image: arch.qcow2
    display: gtk
    bios: /usr/share/ovmf/ovmf_x64.bin   
    networks:
      - netdev: user,id=user,net=192.168.2.0/24,hostname=%h,hostfwd=tcp::%p-:22
        device: virtio-net-pci,netdev=user

provisioner:
    name: chef_zero

    
suites:
- name: default
  run_list:
    - recipe[xil-init::default]
  attributes: {
	"pacman" : {
		"mirror" : "http://192.168.1.103/"
	}
  }
      

